# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jojosardina.github.io
title: JoJo Sardina
email: jojosardina@gmail.com
author: JoJo Sardina
description: > # "Write an awesome description for your new site here. 
  Genetics PhD student at UW-Madison
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/jojo_sci
  - title: github
    url: https://github.com/jojosardina
  - title: linkedin
    url: 
